name: Run deck 
on: push
env: 
  KONG_KONNECT_TOKEN: ${{ secrets.KONG_KONNECT_TOKEN }}
  KONG_CP_NAME: default
  SERVICE_NAME: reqres
  TAG_NAME: api-demo

jobs:
  deploy-my-demo-api:
    runs-on: ubuntu-latest
    steps:
    - name: Setup deck
      uses: kong/setup-deck@v1
      with: 
        deck-version: 1.29.2
    - name: Clone repo
      uses: actions/checkout@v2
    # - name: backup old service config from the cp
    #   run: |
    #     mkdir -p ./spec-backup
    #     deck dump --konnect-addr "https://us.api.konghq.com" --konnect-token ${{ secrets.KONG_KONNECT_TOKEN }} --konnect-control-plane-name ${{ env.KONG_CP_NAME }} -o kong-dev.yaml
    #     cp ./kong-dev.yaml ./spec-backup 
    #     ls -la ./spec-backup
    #     cd ./spec-backup
    #     cat ./kong-dev.yaml
    - name: convert openapi to kong format.
      run: | 
        mkdir generated 
        deck file openapi2kong --inso-compatible -s apis-config/${{ env.SERVICE_NAME }}/openapi-spec.yaml -o generated-spec.yaml
        deck file add-tags -s generated-spec.yaml --selector='services[*]'  {{ env.TAG_NAME }}
    - name: add global plugins and routes plugins to the generated file.
      run: |    
        deck file add-plugins -s generated-spec.yaml  --selector='services[*]' ./common-config/global-plugins/rate-limiting-global.json
        deck file add-plugins -s generated-spec.yaml --selector "$..routes[*][?(@.name=='resqres-example-resource-get')].plugins" ./apis-config/plugins/route.json
    - name: deck validate generated file 
      run : deck file validate generated-spec.yaml
    - name: deck diff generated file
      run : deck gateway diff generated-spec.yaml --konnect-addr "https://eu.api.konghq.com" --konnect-token ${{ secrets.KONG_KONNECT_TOKEN }} --konnect-control-plane-name ${{ secrets.KONG_CP_NAME }} --select-tag ${{ env.TAG_NAME }}
    - name: deck sync generated file
      run : deck gateway sync generated-spec.yaml --konnect-addr "https://eu.api.konghq.com" --konnect-token ${{ secrets.KONG_KONNECT_TOKEN }} --konnect-control-plane-name ${{ secrets.KONG_CP_NAME }} --select-tag ${{ env.TAG_NAME }}