name: Run deck 
on: push
jobs:
  deck-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Setup deck
      uses: kong/setup-deck@v1
      with: 
        deck-version: 2.3.1
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Run deck deck-gateway-sync
      run: deck gateway sync --konnect-addr "https://us.api.konghq.com" #--konnect-token ${{ secrets.KONG_KONNECT_TOKEN }} --konnect-org ${{ secrets.KONG_KONNECT_ORG }} --konnect-env ${{ secrets.KONG_KONNECT_ENV }} --deck-file "deck.yaml" --deck-addr "http://localhost:8001" --deck-insecure-skip-tls-verify