name: Run deck 
on: push
env: 
  KONG_KONNECT_TOKEN: ${{ secrets.KONG_KONNECT_TOKEN }}
  KONG_CP_NAME: dev-demo
  SERVICE_NAME: httpbin

jobs:
  deploy-my-demo-api:
    runs-on: ubuntu-latest
    steps:
    - name: Setup deck
      uses: kong/setup-deck@v1
      with: 
        deck-version: 1.29.2
    - name: Clone repo
      uses: actions/checkout@v2
    - name: install inso 
      run: |
        tar -xf inso-linux-8.4.5.tar.xz 
        ./inso --version
    - name: backup old service config from the cp
      run: |
        mkdir -p ./spec-backup
        deck dump --konnect-addr "https://us.api.konghq.com" --konnect-token ${{ secrets.KONG_KONNECT_TOKEN }} --konnect-control-plane-name ${{ secrets.KONG_CP_NAME }} -o kong-dev.yaml
        cp ./kong-dev.yaml ./spec-backup
        ls -la ./spec-backup
        cd ./spec-backup
        cat ./kong-dev.yaml
    - name: validate openapi spec
      run: inso lint spec $SERVICE_NAME