name: Run deck 
on: push
env: 
  KONG_KONNECT_TOKEN: ${{ secrets.KONG_KONNECT_TOKEN }}
  KONG_CP_NAME: dev-demo
  SERVICE_NAME: reqres

jobs:
  deploy-my-demo-api:
    runs-on: ubuntu-latest
    steps:
    - name: Setup deck
      uses: kong/setup-deck@v1
      with: 
        deck-version: 1.29.2
    - name: Clone repo
      uses: actions/checkout@v2
    - name: backup old service config from the cp
      run: |
        mkdir -p ./spec-backup
        deck dump --konnect-addr "https://us.api.konghq.com" --konnect-token ${{ secrets.KONG_KONNECT_TOKEN }} --konnect-control-plane-name ${{ secrets.KONG_CP_NAME }} -o kong-dev.yaml
        cp ./kong-dev.yaml ./spec-backup
        ls -la ./spec-backup
        cd ./spec-backup
        cat ./kong-dev.yaml
    - name: deck file validate openapi spec
      run: | 
        mkdir generated 
        deck file openapi2kong --inso-compatible -s apis-config/${{ env.SERVICE_NAME }}/openapi-spec.yaml -o generated-spec.yaml 
        cp ./generated-spec.yaml ./generated
        cat ./generated/generated-spec.yaml
    - name: deck file tag 
      run : deck file add-tags --selector='services[*]' reqres
    - name: deck validate generated file 
      run : deck file validate ./generated/generated-spec.yaml
    - name: deck diff generated file
      run : deck gateway diff generated/generated-spec.yaml --konnect-addr "https://us.api.konghq.com" --konnect-token ${{ secrets.KONG_KONNECT_TOKEN }} --konnect-control-plane-name ${{ secrets.KONG_CP_NAME }} --select-tag reqres
