name: Run deck 
on: push
jobs:
  deck-file-openapi:
    runs-on: ubuntu-latest
    steps:
    - name: Setup deck
      uses: kong/setup-deck@v1
      with: 
        deck-version: 1.29.2
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Run deck file openapi
      run: deck file openapi2kong --inso-compatible -s apis-config/demo-api/openapi-spec.yaml -o kong-dev.yaml  
    - name: Run deck diff 
      run: deck diff kong-dev.yaml --konnect-addr "https://us.api.konghq.com" --konnect-token ${{ secrets.KONG_KONNECT_TOKEN }} --konnect-control-plane-name ${{ secrets.KONG_CP_NAME }} 
  deck-diff:
    runs-on: ubuntu-latest
    #make it run only on main branch
    #if{{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Setup deck
      uses: kong/setup-deck@v1
      with: 
        deck-version: 1.29.2
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Run deck deck-diff
      run: deck diff --konnect-addr "https://us.api.konghq.com" --konnect-token ${{ secrets.KONG_KONNECT_TOKEN }} --konnect-control-plane-name ${{ secrets.KONG_CP_NAME }} #--deck-insecure-skip-tls-verify 
  deck-sync:
    needs: deck-diff
    #make it run only on main branch
    #if{{ github.ref == 'refs/heads/main' }}
    # environment:
    #   name: production
    runs-on: ubuntu-latest
    steps:
    - name: Setup deck
      uses: kong/setup-deck@v1
      with: 
        deck-version: 1.29.2
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Run deck deck-gateway-sync
      run: deck sync --konnect-addr "https://us.api.konghq.com" --konnect-token ${{ secrets.KONG_KONNECT_TOKEN }} --konnect-control-plane-name ${{ secrets.KONG_CP_NAME }} #--deck-insecure-skip-tls-verify 